In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv('index_1.csv')

In [31]:
df1.head()

,date,datetime,cash_type,card,money,coffee_name,stream,Stream
0,3/1/2024,15:50.5,card,ANON-0000-0000-0001,38.7,Latte,Stream A,Stream A
1,3/1/2024,19:22.5,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Stream A,Stream A
2,3/1/2024,20:18.1,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Stream A,Stream A
3,3/1/2024,46:33.0,card,ANON-0000-0000-0003,28.9,Americano,Stream A,Stream A
4,3/1/2024,48:14.6,card,ANON-0000-0000-0004,38.7,Latte,Stream A,Stream A

In [32]:
col_to_delete = ['stream', 'Stream']

In [33]:
df1 = df1.drop(columns=col_to_delete)

In [34]:
df1.head()

       date datetime cash_type                 card  money    coffee_name
0  3/1/2024  15:50.5      card  ANON-0000-0000-0001   38.7          Latte
1  3/1/2024  19:22.5      card  ANON-0000-0000-0002   38.7  Hot Chocolate
2  3/1/2024  20:18.1      card  ANON-0000-0000-0002   38.7  Hot Chocolate
3  3/1/2024  46:33.0      card  ANON-0000-0000-0003   28.9      Americano
4  3/1/2024  48:14.6      card  ANON-0000-0000-0004   38.7          Latte

In [28]:
df2 = pd.read_csv('index_2.csv')

In [35]:
df2.head()

       date        datetime cash_type  money            coffee_name
0  2/8/2025  2/8/2025 14:26      cash     15                    Tea
1  2/8/2025  2/8/2025 14:28      cash     15                    Tea
2  2/8/2025  2/8/2025 14:33      card     20               Espresso
3  2/8/2025  2/8/2025 15:51      card     30  Chocolate with coffee
4  2/8/2025  2/8/2025 16:35      cash     27    Chocolate with milk

In [37]:
df1['Stream'] = 'Stream A'
df2['Stream'] = 'Stream B'

In [38]:
merged_df = pd.concat([df1, df2], ignore_index=True)
merged_df.head()

,date,datetime,cash_type,card,money,coffee_name,Stream
0,3/1/2024,15:50.5,card,ANON-0000-0000-0001,38.7,Latte,Stream A
1,3/1/2024,19:22.5,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Stream A
2,3/1/2024,20:18.1,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Stream A
3,3/1/2024,46:33.0,card,ANON-0000-0000-0003,28.9,Americano,Stream A
4,3/1/2024,48:14.6,card,ANON-0000-0000-0004,38.7,Latte,Stream A

In [39]:
merged_df.tail()

,date,datetime,cash_type,card,money,coffee_name,Stream
3893,3/23/2025,3/23/2025 14:55,cash,NaN,30.0,Cappuccino,Stream B
3894,3/23/2025,3/23/2025 15:15,card,NaN,25.0,Irish whiskey,Stream B
3895,3/23/2025,3/23/2025 17:59,card,NaN,28.0,Super chocolate,Stream B
3896,3/23/2025,3/23/2025 18:01,card,NaN,28.0,Vanilla with Irish whiskey,Stream B
3897,3/23/2025,3/23/2025 21:23,card,NaN,29.0,Coffee with Irish whiskey,Stream B

In [49]:
merged_df['card'] = merged_df['card'].fillna("")

In [50]:
merged_df.tail()

,date,datetime,cash_type,card,money,coffee_name,Stream
3893,3/23/2025,3/23/2025 14:55,cash,,30.0,Cappuccino,Stream B
3894,3/23/2025,3/23/2025 15:15,card,,25.0,Irish whiskey,Stream B
3895,3/23/2025,3/23/2025 17:59,card,,28.0,Super chocolate,Stream B
3896,3/23/2025,3/23/2025 18:01,card,,28.0,Vanilla with Irish whiskey,Stream B
3897,3/23/2025,3/23/2025 21:23,card,,29.0,Coffee with Irish whiskey,Stream B

In [54]:
merged_df.duplicated().sum()

np.int64(2)

In [55]:
duplicated_rows = merged_df[merged_df.duplicated()]
print(duplicated_rows)

           date         datetime cash_type card  money          coffee_name  \
3747  2/26/2025   2/26/2025 9:41      cash        25.0  Americano with milk
3892  3/23/2025  3/23/2025 10:25      cash        25.0  Americano with milk

        Stream
3747  Stream B
3892  Stream B